// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0niZa__jyNuXprw12evyGOMR5K80TiQo',
    appId: '1:397644378970:web:c28555a2a5731b8a2ef963',
    messagingSenderId: '397644378970',
    projectId: 'findmyfun-c0acc',
    authDomain: 'findmyfun-c0acc.firebaseapp.com',
    storageBucket: 'findmyfun-c0acc.appspot.com',
    measurementId: 'G-02NGZVYQFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPB4b27ioy2to5KQNf7WrKd5oU7bc7w2Y',
    appId: '1:397644378970:android:9630b64222801a972ef963',
    messagingSenderId: '397644378970',
    projectId: 'findmyfun-c0acc',
    storageBucket: 'findmyfun-c0acc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz4I7fvFR0YFK7bKAJiSYTjdFg7boLIxs',
    appId: '1:397644378970:ios:3cee2cb7e6bea2462ef963',
    messagingSenderId: '397644378970',
    projectId: 'findmyfun-c0acc',
    storageBucket: 'findmyfun-c0acc.appspot.com',
    iosClientId: '397644378970-ql4jhsbq0tfm4u8et65se0hcaee4cjct.apps.googleusercontent.com',
    iosBundleId: 'com.isppg8.findmyfun',
  );
}
